### ISSUE TITLE
问题：加载不到golang.org/x相关包

### ISSUE THREAD

**Issue by 4color** [goproxy/goproxy.cn#57]
## 当你执行 `go version` 命令后的输出结果是什么？

<pre>
$ go version

go version go1.13.3 windows/amd64
</pre>

## 当你执行 `go env` 命令后的输出结果是什么？

<details>
<summary><code>go env</code> 的输出结果</summary>
<br>
<pre>
$ go env

set GO111MODULE=on
set GOARCH=amd64
set GOBIN=D:\Developer\GoWorks\install\bin
set GOCACHE=C:\Users\4color\AppData\Local\go-build
set GOENV=C:\Users\4color\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=E:\MyProjects\SKDevPlatform\SKDevPlatform
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=D:\Developer\GoWorks\install
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\Developer\GoWorks\install\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\4color\AppData\Local\Temp\go-build586634794=/tmp/go-build -gno-record-gcc-switches
</pre>
</details>

## 你期望看到的结果是什么？

go list 

## 你实际看到的结果是什么？

go list -m: unrecognized import path "cloud.google.com/go" (https fetch: Get https://cloud.google.com/go?go-get=1: dial tcp [2404:6800:4012::200e]:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)
go list -m: unrecognized import path "golang.org/x/lint" (https fetch: Get https://golang.org/x/lint?go-get=1: dial tcp 216.239.37.1:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)
go list -m: unrecognized import path "golang.org/x/mod" (https fetch: Get https://golang.org/x/mod?go-get=1: dial tcp 216.239.37.1:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)
go list -m: unrecognized import path "golang.org/x/oauth2" (https fetch: Get https://golang.org/x/oauth2?go-get=1: dial tcp 216.239.37.1:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)
go list -m: unrecognized import path "golang.org/x/sync" (https fetch: Get https://golang.org/x/sync?go-get=1: dial tcp 216.239.37.1:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)
go list -m: unrecognized import path "golang.org/x/time" (https fetch: Get https://golang.org/x/time?go-get=1: dial tcp 216.239.37.1:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)
go list -m: unrecognized import path "golang.org/x/tools" (https fetch: Get https://golang.org/x/tools?go-get=1: dial tcp 216.239.37.1:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)
go list -m: unrecognized import path "google.golang.org/appengine" (https fetch: Get https://google.golang.org/appengine?go-get=1: dial tcp 216.239.37.1:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)
go list -m: unrecognized import path "google.golang.org/genproto" (https fetch: Get https://google.golang.org/genproto?go-get=1: dial tcp 216.239.37.1:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)
go list -m: unrecognized import path "google.golang.org/grpc" (https fetch: Get https://google.golang.org/grpc?go-get=1: dial tcp 216.239.37.1:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)

**Comment by aofei** [comment]
你好，你的输出结果表明你并没有在使用 Go module proxy，而是走的直连，因为如果你在使用 Go module proxy 的话那么你的所有连接都应该是以 https://goproxy.cn 为前缀的才对。

请你确认一下你执行 `go list` 时所在的目录是什么，是否包含 `go.mod` 文件。

**Comment by 4color** [comment]
谢谢，可以了。开发工具里还要再设置一下，不能用直连

**Comment by aofei** [comment]
好的，鉴于问题已解决我就关闭这个 Issue 了哈，如果还有其他问题欢迎随时提问。😊

**Comment by fengtuo58** [comment]
I:\Jenkins\workspace\Enterlite-Win-Release\3rd\spalib\go.mod:13: require golang.zx2c4.com/wireguard: version "master" invalid: Get https://proxy.golang.org/golang.zx2c4.com/wireguard/@v/master.info: dial tcp 172.217.27.145:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
I:\Jenkins\workspace\Enterlite-Win-Release\3rd\spalib\go.mod:14: require golang.zx2c4.com/wireguard/windows: version "master" invalid: Get https://proxy.golang.org/golang.zx2c4.com/wireguard/windows/@v/master.info: dial tcp 172.217.160.113:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
I:\Jenkins\workspace\Enterlite-Win-Release\3rd\spalib\go.mod:17: replace golang.zx2c4.com/wireguard/windows: version "master" invalid: Get https://proxy.golang.org/golang.zx2c4.com/wireguard/windows/@v/master.info: dial tcp 172.217.160.113:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
I:\Jenkins\workspace\Enterlite-Win-Release\3rd\spalib\go.mod:19: replace golang.zx2c4.com/wireguard: version "master" invalid: Get https://proxy.golang.org/golang.zx2c4.com/wireguard/@v/master.info: dial tcp 172.217.27.145:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
@aofei 帮忙看一下这个，时好时坏

**Comment by aofei** [comment]
@fengtuo58 

你好，你遇到的这个错误表明你的 `GOPROXY` 环境变量并没有配置正确，所以你并没有在使用 [goproxy.cn](https://goproxy.cn)。

如果你是终端环境，你可以检查一下你的 `go env`。如果你是 GoLand 之类的 IDE，那么需要注意在 IDE 中还需要在单独设置一次 `GOPROXY` 等环境变量的，因为据我所知 GoLand 是会忽略系统环境变量而按照自己的一套来的。

顺便说一下，下次你可以开个新 issue 的，尽量不要在已经关闭的 issue 中回复。
