### ISSUE TITLE
Bug: TLS handshake timeout for **gcexportdata** and **astutil**

### ISSUE THREAD

**Issue by 6543** [goproxy/goproxy.cn#75]
## What is the output when you execute the `go version` command?

<pre>
$ go version

go version go1.14.1 linux/amd64

</pre>

## What is the output when you execute the `go env` command?

<details>
<summary><code>go env</code> Output</summary>
<br>
<pre>
$ go env

GO111MODULE=""
--
7 | GOARCH="amd64"
8 | GOBIN=""
9 | GOCACHE="/root/.cache/go-build"
10 | GOENV="/root/.config/go/env"
11 | GOEXE=""
12 | GOFLAGS=""
13 | GOHOSTARCH="amd64"
14 | GOHOSTOS="linux"
15 | GOINSECURE=""
16 | GONOPROXY=""
17 | GONOSUMDB=""
18 | GOOS="linux"
19 | GOPATH="/go"
20 | GOPRIVATE=""
21 | GOPROXY="direct,https://goproxy.cn"
22 | GOROOT="/usr/local/go"
23 | GOSUMDB="sum.golang.org"
24 | GOTMPDIR=""
25 | GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
26 | GCCGO="gccgo"
27 | AR="ar"
28 | CC="gcc"
29 | CXX="g++"
30 | CGO_ENABLED="1"
31 | GOMOD=""
32 | CGO_CFLAGS="-g -O2"
33 | CGO_CPPFLAGS=""
34 | CGO_CXXFLAGS="-g -O2"
35 | CGO_FFLAGS="-g -O2"
36 | CGO_LDFLAGS="-g -O2"
37 | PKG_CONFIG="pkg-config"
38 | GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build354326419=/tmp/go-build -gno-record-gcc-switches"

</pre>
</details>

## What did you do?

```
$ get -u github.com/mgechev/revive

unrecognized import path "golang.org/x/tools/go/gcexportdata": https fetch: Get "https://golang.org/x/tools/go/gcexportdata?go-get=1": net/http: TLS handshake timeout
```

## What is the behavior of the bug?

a TLS handshake timeout

## Do you have any guesses?

sory I dont.

Sory I dont. But I'm waiting to have this fixed about 17 days ...
the revive tool is used in gitea's go-sdk CI:
https://drone.gitea.com/gitea/go-sdk

the CI task with env info: https://drone.gitea.com/gitea/go-sdk/483/1/3
normal CI task witch is failing: https://drone.gitea.com/gitea/go-sdk/474/1/3

**Comment by 6543** [comment]
repository: https://gitea.com/gitea/go-sdk
is used in make target revive

**Comment by aofei** [comment]
Hi @6543,

The problem is that you set `GOPROXY` wrong. It should be `GOPROXY=https://goproxy.cn,direct`，but you set it to `GOPROXY=direct,https://goproxy.cn`. In your setup, `go` will never use [goproxy.cn](https://goproxy.cn) or any other proxy, it will only pull the module version by going ***directly*** from the origin code source.

**Comment by 6543** [comment]
Hi @aofei,

If it would be that easy ..., 
the order you sugest dosent work either: https://drone.gitea.com/gitea/go-sdk/505/1/3

**Comment by aofei** [comment]
Well, it still shows that you are using a wrong setup. Because it still downloading module versions directly (without using any Go module proxies). What's the environment variables now?

**Comment by aofei** [comment]
Or you can try setting the value of GOPROXY to "https://goproxy.cn" only, that is, ***remove the ",direct"***. This will ensure that go will only use the Go module proxy, and never download anything **directly** from the source code.

**Comment by 6543** [comment]
@aofei tryed your suggestion:
It worked once: https://drone.gitea.com/gitea/go-sdk/509
and failed twice then: https://drone.gitea.com/gitea/go-sdk/510, https://drone.gitea.com/gitea/go-sdk/511

**Comment by aofei** [comment]
It's not your mistake, I just found that it has been hard-coded into the ".drone.yml" file (see https://gitea.com/gitea/go-sdk/src/branch/master/.drone.yml#L39). So you will fail until you correct this file.

**Comment by 6543** [comment]
Sory I'll explain our setup: when a new commit is pushed to a pullrequest, drone CI is running tests. Drone use the config file of the Headbranch so it's not hardcoded ... the version you have too look at is: https://gitea.com/6543/go-sdk/src/branch/fix-test/.drone.yml#L39

Related PR: https://gitea.com/gitea/go-sdk/pulls/287

**Comment by aofei** [comment]
Okay, let's investigate it together.

First, please add a `go env` command to the `.drone.yml`'s `commands` section (before the `make clean` line, https://gitea.com/6543/go-sdk/src/branch/fix-test/.drone.yml#L46):

```yaml
commands:
  - go env
  - make clean
  - make vet
  - make revive
  - make build
  - curl --noproxy "*" http://gitea:3000/api/v1/version # verify connection to instance
  - make test
```

Then start a CI task and tell me its URL, I need to know the detailed configurations.

**Comment by aofei** [comment]
BTW, I think I need explain to you how Go modules work in your scenario.

When the `GOPROXY` is `https://goproxy.cn`:

1. `go` command found that you need the `golang.org/x/tools/go/gcexportdata` package
2. `go` command does not know if the `golang.org/x/tools/go/gcexportdata` is a **module path** (spoiler, it's not, it's just a **import path**)
3. `go` command starts **"module path estimation"** based on your `GOPROXY` setting
4. `go` command sent a Go module proxy request (https://goproxy.cn/golang.org/x/tools/go/gcexportdata/@v/list) and received a 404 response
5. `go` command trims the original import path to `golang.org/x/tools/go` (discard the last path element)
6. `go` command send a Go module proxy request (https://goproxy.cn/golang.org/x/tools/go/@v/list) and received a 404 response
7. `go` command trims the original import path to `golang.org/x/tools` (discard one more last path element)
8. `go` command send a Go module proxy request (https://goproxy.cn/golang.org/x/tools/@v/list) and received a 200 response with an empty body
9. `go` command send a Go module proxy request (https://goproxy.cn/golang.org/x/tools/@latest) and received a 200 response with an module info body
10. `go` command completes **"module path estimation"**

When the `GOPROXY` is `https://goproxy.cn,direct`:

1. `go` command found that you need the `golang.org/x/tools/go/gcexportdata` package
2. `go` command does not know if the `golang.org/x/tools/go/gcexportdata` is a **module path** (spoiler, it's not, it's just a **import path**)
3. `go` command starts **"module path estimation"** based on your `GOPROXY` setting
4. `go` command sent a Go module proxy request (https://goproxy.cn/golang.org/x/tools/go/gcexportdata/@v/list) and received a 404 response
5. ***`go` command falls back to the `direct` you specified in the GOPROXY comma list***
6. `go` command sent a traditional `go get` request (https://golang.org/x/tools/go/gcexportdata?go-get=1) and a timeout occurred due to the network of your CI server
7. `go` command fails **"module path estimation"**

So, you can see that if there is a request like `https://golang.org/x/tools/go/gcexportdata?go-get=1`, then your related `go` command absolutely uses no proxy. Because if it uses a certain proxy, then this situation of going directly to the source will not occur, instead, all request URLs will begin with that proxy (like https://goproxy.cn/golang.org/x/tools/go/gcexportdata/@v/list).

**Comment by 6543** [comment]
@aofei thanks for the great explanation!

and the go env is in the issue body already ... but I added it again so you can look at this yourself:
 * PR: https://gitea.com/gitea/go-sdk/pulls/287/files
 * CI: https://drone.gitea.com/gitea/go-sdk/521/1/3

**Comment by aofei** [comment]
I see... well, can you set `GO111MODULE` to `on` and try again?

**Comment by aofei** [comment]
> I see... well, can you set `GO111MODULE` to `on` and try again?

Explanation: The reason I asked this is because I found that `GOMOD` in your `go env` output is empty. In fact, when it's empty (and with `GO111MODULE` is also empty), the Go modules feature is disabled, which means that you're using the traditional GOPATH-mode. In other words, `GO111MODULE` is equal to `off` at this time.

**Comment by aofei** [comment]
https://drone.gitea.com/gitea/go-sdk/522

Congrats! 🍻

So I recommend adding the following two lines to the `environment` section of the `.drone.yml` file for all your projects, this will permanently solve all similar problems you encounter:

```yml
GO111MODULE: "on"
GOPROXY: "https://goproxy.cn"
```

You can discuss this with @lunny.

**Comment by 6543** [comment]
sure - and thanks for helping me out :+1:

**Comment by lunny** [comment]
Thanks @aofei and @6543 !!!
