### ISSUE TITLE
Question: Can i remove cached version module?

### ISSUE THREAD

**Issue by billcoding** [goproxy/goproxy.cn#80]

**Comment by aofei** [comment]
Sorry, you can't. Whenever possible, the Go module proxy (especially [goproxy.cn](https://goproxy.cn)) aims to cache module files in order to avoid breaking builds for people that depend on your module versions, so a bad module version may still be available in the Go module proxy even if it's not available at the origin. The same situation applies if some authors delete their entire repositories.

**Comment by billcoding** [comment]
Got it, thanks.
----- 原始邮件 -----
发件人：Aofei Sheng <notifications@github.com>
收件人："goproxy/goproxy.cn" <goproxy.cn@noreply.github.com>
抄送人："@Billcoding" <wangmiao07@sina.com>,  Author <author@noreply.github.com>
主题：Re: [goproxy/goproxy.cn] Question: Can i remove cached version module? (#80)
日期：2020年04月26日 13点10分


Sorry, you can't. Whenever possible, the Go module proxy (especially goproxy.cn) aims to cache module files in order to avoid breaking builds for people that depend on your module versions, so a bad module version may still be available in the Go module proxy even if it's not available at the origin. The same situation applies if some authors delete their entire repositories.

&mdash;

**Comment by aofei** [comment]
Closing due to the question has been answered.
